#!/usr/bin/env python3
import os
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
RESTART_DELAY = 3

COLLECTORS = [
    ("system-monitor", ["bin/sysmon-collect", "--serve"], []),
    ("process-monitor", ["bin/procmon-collect", "--serve"], []),
    ("router-monitor", ["bin/routermon-collect", "--serve"], ["-S"]),
    ("system-log", ["bin/logmon-collect", "--serve"], []),
    ("portals", ["bin/portal-friends", "--serve"], []),
]


def start(widget, arguments, flags):
    script = os.path.join(ROOT, widget, arguments[0])
    return subprocess.Popen([sys.executable, *flags, script, *arguments[1:]])


def main():
    overlay = os.path.join(ROOT, "service", "monitor-overlay")
    if os.path.isfile(overlay):
        subprocess.run([sys.executable, overlay, "hide"], check=False)
    running = {}
    for widget, arguments, flags in COLLECTORS:
        if os.path.isfile(os.path.join(ROOT, widget, arguments[0])):
            running[start(widget, arguments, flags).pid] = (widget, arguments, flags, time.monotonic())
    if not running:
        sys.stderr.write("konveyor-widgets: no collectors found\n")
        return 1
    while running:
        pid, status = os.wait()
        if pid not in running:
            continue
        widget, arguments, flags, started = running.pop(pid)
        sys.stderr.write(f"{widget}: collector exited with status {os.waitstatus_to_exitcode(status)}, restarting\n")
        time.sleep(max(0, RESTART_DELAY - (time.monotonic() - started)))
        running[start(widget, arguments, flags).pid] = (widget, arguments, flags, time.monotonic())
    return 0


if __name__ == "__main__":
    sys.exit(main())
